baseURL: 'https://vcabeli.github.io'
languageCode: 'en-us'
title: 'VCabeli'
theme:
- 'PaperMod'
- hugo-cite
disqusShortname: vcabe-li.disqus.com/admin

params:
    disableThemeToggle: true

    homeInfoParams:
        Title: Vincent's blog
        Content: Disgressions about causality inference, information theory and maybe more !

    comments: true
