baseURL: 'https://vcabe.li'
languageCode: 'en-us'
title: 'VCabeli'
theme:
- 'PaperMod'
- hugo-cite
disqusShortname: vcabe-li

params:
    disableThemeToggle: true

    homeInfoParams:
        Title: Vincent's blog
        Content: Digressions about causal inference, information theory and maybe more !

    comments: true
